# Generated by Django 5.2.7 on 2025-10-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='risk_profile',
            field=models.CharField(choices=[('CON', 'Conservador'), ('MOD', 'Moderado'), ('AGR', 'Agresivo')], default='MOD', max_length=3),
        ),
    ]
