# Generated by Django 5.2.7 on 2025-11-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuariopersonalizado_two_factor_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='notif_inicio_sesion',
            field=models.BooleanField(default=True, verbose_name='Alerta de inicio de sesión'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='notif_marketing',
            field=models.BooleanField(default=False, verbose_name='Correos de marketing'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='priv_compartir_datos',
            field=models.BooleanField(default=True, verbose_name='Compartir datos anónimos'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='priv_perfil_publico',
            field=models.BooleanField(default=False, verbose_name='Perfil público'),
        ),
    ]
