"""
Django settings for crypto_trading project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
import os

PORT = os.environ.get("PORT", 8000)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bq$3r_228n$h+8^-^g$^g6r4hvqf@28u%r92ut1bvyuwo_--+b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

#CADA VEZ QUE SE CREA UNA APP, HAY QUE AGREGARLA AQUI
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'dashboard',
    "trading",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crypto_trading.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crypto_trading.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'bloomberg'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'alianzalima1'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('es', _('Español')),
    ('en', _('Inglés')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',  # Carpeta donde Django guardará los archivos de traducción
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'usuarios.UsuarioPersonalizado'

# Configuración del backend de correo electrónico para desarrollo CONSOLA
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'CryptoTrade <no-reply@cryptotrade.local>'

"""
# Configuración del backend de correo electrónico para desarrollo CONSOLA
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'email-smtp.us-east-1.amazonaws.com'  # Cambia si tu región es otra
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Tus credenciales SMTP de SES
EMAIL_HOST_USER = 'AKIA5X2JUNPXARGNEBHI'  # Nombre de usuario SMTP
EMAIL_HOST_PASSWORD = 'BKyhjdP2mBzZ96XW5ycyBmhsoiOExyhHeExNaA0X0Abl'  # Contraseña SMTP

# Dirección que aparecerá en el campo "De" de los correos
DEFAULT_FROM_EMAIL = 'alessandro.trinidad09@gmail.com'

ALLOWED_HOSTS = ['.elasticbeanstalk.com', 'crypto-trading-env.eba-3ep8huja.us-east-1.elasticbeanstalk.com', 'localhost',"*"]
"""
""""
# Soporte
SUPPORT_EMAIL = "alessandro.trinidad09@gmail.com"
"""

"""""
# Usamos SMTP de Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# TU CORREO GMAIL (El que usaste para generar la clave)
EMAIL_HOST_USER = 'favio.tirado.13@gmail.com' 

# LA CONTRASEÑA DE APLICACIÓN (Los 16 caracteres, sin espacios)
EMAIL_HOST_PASSWORD = 'wyraamwypprxbssj' 

# Remitente por defecto
DEFAULT_FROM_EMAIL = 'CryptoTrade <favio.tirado.13@gmail.com>'

# Correo donde recibirás los mensajes del formulario de contacto
SUPPORT_EMAIL = 'favio.tirado.13@gmail.com'
"""