# Generated by Django 5.2.7 on 2025-10-16 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price_usd', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, help_text='Precio por unidad en USD al momento de la operación', max_digits=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='trading.activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=0.0, help_text='Cantidad de la criptomoneda que posee el usuario', max_digits=20)),
                ('average_price', models.DecimalField(decimal_places=8, default=0.0, help_text='Precio promedio al que se adquirió el activo', max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio_entries', to='trading.activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
                'unique_together': {('user', 'asset')},
            },
        ),
    ]
